version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing AWS CLI"
      - npm install -g aws-cli

  pre_build:
    commands:
      - echo "Installing project dependencies"
      - npm install

  build:
    commands:
      - echo "Building React app"
      - npm run build

  post_build:
    commands:
      - echo "Deploying to S3"
      - aws s3 sync build/ s3://ecommerce-ragul --acl public-read
      - echo "React app deployment to S3 complete!"

artifacts:
  files:
    - '**/*'
